### ISSUE TITLE
Mobile notifications on a teem are delivered to community participants

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#156]
Notifications from a chat message are delivered to community participants. They should be delivered to participants of that teem only

**Comment by atfornes** [comment]
Since we changed SwellRT subscritions to be managed as blacklist (https://github.com/P2Pvalue/swellrt/commit/951cfe7775ad4079edd8da1a855afa3a81175324), an user has to unsubscribe from every wave she visits not to receive notifications.

We could try to add a condition in SwellRT event rules, but current implementation does not allow to check for the membership of an item in a list, making it imposible handle from here. See https://github.com/P2Pvalue/swellrt/blob/master/src/org/swellrt/server/box/events/EventRule.java#L252.

I am waiting for @pablojan, @atd and @llopv opinions on this before continuing working in this issue.

**Comment by atd** [comment]
What was the rationale behind subscribing visitors to waves? I have been lately wondering why we had two lists for (what I though) was the same issue. In other words, I expected wave participants to be the same as project participants

**Comment by atd** [comment]
Fixed in SwellRT
