### ISSUE TITLE
Avatars are not shown in the app

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#179]
We have to allow content from swellrt in config.xml

**Comment by atfornes** [comment]
![captura de pantalla de 2016-03-23 14 53 13](https://cloud.githubusercontent.com/assets/7475584/13989153/052a5622-f107-11e5-908f-677f6cd66fee.png)

The problem is with the images trying to be loaded over HTTP instead of over HTTPS.

@pablojan, should we fix this in SwellRT? I believe that if the request is done over https, the url should be returned with https. I believe the follwing is the function call to review, right? https://github.com/P2Pvalue/swellrt/blob/master/src/org/swellrt/server/box/servlet/AccountService.java#L552

**Comment by atd** [comment]
Last SwellRT version fixes this issue
