### ISSUE TITLE
Link to share is not visible

### ISSUE THREAD

**Issue by cynicaldevil** [P2Pvalue/teem#181]
Whenever I click on the 'Share workspace' button either from the drop down menu on the top right or the button in the bottom right, I see a widget pop up saying 'link to share', but there's no link displayed.
![screenshot from 2016-03-19 13-36-55](https://cloud.githubusercontent.com/assets/11256206/13897494/8f36344e-edd8-11e5-9f6a-4a1513369e79.png)
Operating system: ubuntu GNOME 15.10
Browser: Firefox Developer Edition 47.0

**Comment by atfornes** [comment]
@cynicaldevil thanks for sharing but I can not reproduce the issue,

I have tried chromium and Firefox 45.0.1 (last stable version), I have not tried with the Firefox Developer Edition, but it seems like an issue with that version of Firefox rather than with our app.

Can you please share the messages of the browser console when that happen?

thanks!

**Comment by atd** [comment]
@llopv has recently fixed this modal. Please reopen if it still happens
