### ISSUE TITLE
Share modal close links and title are missing

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#198]

**Comment by prastut** [comment]
![a8cd0770-d231-4972-8c6d-1484e54e1d7c](https://cloud.githubusercontent.com/assets/10279686/14868129/acda5b62-0ce9-11e6-9d48-a8dcd1279cad.jpg)


@atd I can see the Title and the close links though they are hard to see because of the color scheme. Does this issue wants us to solve the color scheme for the title?

**Comment by prastut** [comment]
Also since a key-press directive is being developed in PR #251 , this Share modal can also be closed by escape key.

**Comment by atd** [comment]
@prastut yes, this issue is about solving the color scheme. After implementing the new design and using material design, we have a kind of mess with modal headers. We should unify the css and html so all modals use the same structure in the html and the same css classes

Regarding #251, yes, it would be awesome if it worked for this modal, (and the others that can be safely closed by users)

**Comment by atfornes** [comment]
already fixed
