### ISSUE TITLE
Check inputs are not clear

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#212]
Check button besides edit title pad is not clear for some users

![image](https://cloud.githubusercontent.com/assets/26228/14102365/747bd7de-f59a-11e5-9cc7-8e1bd1a83d27.png)

**Comment by elenamv** [comment]
I think we can put only these one (and eliminate the cancel icon, because you can delete with your keyboard and its a standard
![ok_title](https://cloud.githubusercontent.com/assets/16928147/14102766/d7e90f92-f59c-11e5-8ba7-d70d9765013b.png)
We need finer icons so that they can put larger in certain types of actions. This one is from google material design...i dont know if we can use that
https://github.com/google/material-design-icons

**Comment by atd** [comment]
Still it is confusing. The user though the icon meant the title was valid

**Comment by elenamv** [comment]
You´re right.
Maybe we don´t need an icon, and its more simple: when you edit your community, you edit all text fields as the first time you created.

**Comment by atfornes** [comment]
We have a new interface now, close as not applicable
