### ISSUE TITLE
Redirect to info tab when cannot see the chat tab

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#246]
If the user gets a link to the chat and she is not participating in a Teem, or she isn't logged in, she should be redirected to the info tab. Currently you see a blank chat tab

**Comment by prastut** [comment]
@atd, @llopv need some help. I tried the following approaches:

* Since the tabs are being initialized by SharedState I tried the following:
  ```
function currentTab() {
      if(!$scope.project.isContributor()){
        if( $location.search().tab === 'chat'){
          return 'pad';
        }
      }
      return $location.search().tab || 'pad';
    }

SharedState.initialize($scope, 'projectTab', {
      defaultValue: currentTab()
});
  ```
  The problem with this is that $scope.project doesn't get defined and therefore it has no method isContributor to check. I thought since the controller already has ProjectsSvc factory injected, it won't be an issue.

* Next I tried passing ProjectsSvc as a DI to SharedState 
    ```
function currentTab(contributor) {
      if(!contributor){
        if( $location.search().tab === 'chat'){
          return 'pad';
        }
      }
      return $location.search().tab || 'pad';
    }

SharedState.initialize($scope, 'projectTab', 'ProjectsSvc' {
      defaultValue: currentTab($scope.project.isContributor())
});
  ```
 Turns out by reading the documentation for [SharedState.initialize](http://mobileangularui.com/docs/module:mobile-angular-ui/module:core/module:sharedstate/#initialize), I can't do this.

* Then after the reading the above documentation, I tried the following to log the currentval and then apply a condition to the same, no such luck:
  ```
 $scope.$on('mobile-angular-ui.state.initialized.projectTab', function(currentVal){
      console.log(currentVal);
    });

```

I can feel a lot of conceptual flaws in my understanding of DI and scopes. Let me know how to improve on this front.

**Comment by atd** [comment]
@prastut I think you have digged so far!

The problem is that project loading is a call to the backend (SwellRT), which is done asynchronously, so you have the project after the template has been compiled (despite you don't see it because of the loading spinner).

The place when you just get the project and you can already do the check is https://github.com/P2Pvalue/teem/blob/master/src/js/controllers/project.js#L115

**Comment by prastut** [comment]
@atd I tried this, coming up with errors + I feel you can tell me a better way to do this:

```
SessionSvc.onLoad(function(){
      Loading.show(ProjectsSvc.findByUrlId($route.current.params.id)).
        then(function(project) {
          $scope.project = project;
          $scope.populateUserSelector();
      
          if($location.search().tab === 'chat' && !$scope.project.isContributor()){
              $location.search({tab: 'pad'});
              $scope.$apply(); // Did this since the page was not changing, only the URL was resolving
          }

          CommunitiesSvc.all({ ids: project.communities }).then(function (communities) {
            $timeout(function() {
              $scope.communities = communities;
            });
          });
        });
    });
```

Since the page was not resolving to pad, I included $scope.$apply. It throws an error that the $digest cycle is still in process. I could use a $timeout function but I feel that logic is weird. 

I also tried this. No such luck:

```
 $scope.$on('$locationChangeStart', function(event, next) {
      
      if(next.split('?')){
        if(next.split('?')[1].split('=')[1] === 'chat' && !$scope.project.isContributor()){
          $location.search({tab: 'pad'});
        }
      }  

    });
```

Question. According to me their are two ways to solve this issue:
* Check for the next URL and therefore go straight to that particular URL. Requires no refreshing process.
* When you have landed on the URL, check for the current URL and then redirect it. I think it would require refresh. 

Want to know conceptually what is happening.

**Comment by atd** [comment]
@prastut the digest error is quite typical in angular, you will see we are using `$timeout` a lot in the code. We found it is the best way to deal with it

Regarding the issue, what about using `SharedState` (like when you click on one tab) instead of `$location`. It will change the url for you https://github.com/P2Pvalue/teem/blob/master/src/js/controllers/project.js#L160

**Comment by prastut** [comment]
@atd I tried the above earlier. Didn't post it here since logically the code will only work, when you **change** a tab, to when you go directly for the tab. Since we are redirecting to 'pad' tab for the following 2 reasons:
* When user get's a share link like this: `http://localhost:8000/#/teems/bG9jYWwubmV0L3MrYzdyMW5BV0FzV0E?tab=chat`
* When `showProject(project, 'chat')` is called from the project page, when user clicks on the chat icon. 

Both these instances don't lead to a tab change.

**Comment by prastut** [comment]
@atd please review the above PR. I have another question for you:

* I was trying this based on the [this documentation:](http://mobileangularui.com/docs/module:mobile-angular-ui/module:core/module:sharedstate/#initialized)

```
 $scope.$on('mobile-angular-ui.state.initialized.projectTab', function(e, currentVal) {
    console.log(e); // logs the event
    console.log(currentVal); //should log the currentval that has been initialized to projectTab but returns undefined
 });
```

I was trying to check the current value and then write the conditions. Also this only  works or logs when I comment the following section:
```
function currentTab() {
      return $location.search().tab || 'pad';
    }

    SharedState.initialize($scope, 'projectTab', {
      defaultValue: currentTab()
    });
```

What is possibly going wrong?

**Comment by prastut** [comment]
@atd please review the above PR. I have another question for you:

* I was trying this based on the [this documentation:](http://mobileangularui.com/docs/module:mobile-angular-ui/module:core/module:sharedstate/#initialized)

```
 $scope.$on('mobile-angular-ui.state.initialized.projectTab', function(e, currentVal) {
    console.log(e); // logs the event
    console.log(currentVal); //should log the currentval that has been initialized to projectTab but returns undefined
 });
```

I was trying to check the current value and then write the conditions. Also this only  works or logs when I comment the following section:
```
function currentTab() {
      return $location.search().tab || 'pad';
    }

    SharedState.initialize($scope, 'projectTab', {
      defaultValue: currentTab()
    });
```

What is possibly going wrong?

**Comment by atd** [comment]
@prastut I don't know.. I would have to dig deeper into it
