### ISSUE TITLE
SwellRT domain in session menu is useless

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#288]
![image](https://cloud.githubusercontent.com/assets/26228/16611332/ef8a2048-4360-11e6-8b2d-30bae74ef913.png)

@llopv @elenamv is there any rationale for adding swellrt address in session menu?

Currently we are not federated with anyone. Are users understanding what is `@prototype.p2pvalue.eu`? What is the value for them?

**Comment by elenamv** [comment]
We put the mail with you are sign in but i´m not sure that it helps or is only "noise"

**Comment by atd** [comment]
Thank you for the clarification @elenamv I see the rationale on that.

Note that `atd@prototype.p2pvalue.eu` is not my email!

**Comment by llopv** [comment]
Yes, I have to refactor the User service to fetch user's profile data, and get the email from there.

Anyway, this two fields could be *name* and *nick* instead of *name* and *email* (in designs) or *nick* and *id* (currently). @pablojan agrees in having actual names (i. e. David Llop) stored in SwellRT, but he needs to refactor some things.

BTW, I can erase the second line until we have it more clear.

**Comment by atd** [comment]
@llopv let's do what provides our users with more value. What would you like to view in that line?

**Comment by llopv** [comment]
If we integrate user's names, in the second line I would like to see their nicks.

But this opens a new question. Where we ask for user's name?
